/**
 * design-tokens + main + components → tek site.css (render-blocking istek sayısını azaltır).
 * Kullanım: node scripts/build-css.js
 */
const fs = require('fs');
const path = require('path');

const CSS_DIR = path.join(__dirname, '..', 'assets', 'css');
const OUT = path.join(CSS_DIR, 'site.css');

function stripFontImport(css) {
  return css.replace(/@import\s+url\([^)]*fonts\.googleapis\.com[^)]*\)\s*;?\s*/gi, '');
}

function buildSiteCss() {
  const tokens = stripFontImport(fs.readFileSync(path.join(CSS_DIR, 'design-tokens.css'), 'utf8')).trim();
  const main = fs
    .readFileSync(path.join(CSS_DIR, 'main.css'), 'utf8')
    .replace(/^@import\s+['"]design-tokens\.css['"];\s*/m, '')
    .trim();
  const components = fs.readFileSync(path.join(CSS_DIR, 'components.css'), 'utf8').trim();

  const bundle = `/* Generated by scripts/build-css.js — kaynak: design-tokens + main + components */\n${tokens}\n\n${main}\n\n${components}\n`;
  fs.writeFileSync(OUT, bundle, 'utf8');
  const kb = (Buffer.byteLength(bundle, 'utf8') / 1024).toFixed(1);
  console.log(`site.css yazıldı (${kb} KiB)`);
  return OUT;
}

if (require.main === module) {
  buildSiteCss();
}

module.exports = { buildSiteCss };
